# -*- mode: python ; coding: utf-8 -*-

datas_list = [
    ( 'img/*', 'img' ),
    ( 'img/icon.ico', 'ico' )
]

includes_list = [
    'cycler',
    'kiwisolver',
    'matplotlib',
    'mplcyberpunk',
    'numpy',
    'packaging',
    'pyparsing',
    'PySide6',
    'PySide6_Addons',
    'PySide6_Essentials',
    'scipy',
    'shiboken6',
    'six',
    'termcolor'
]

excludes_list = [
    'absl-py',
    'ale-py',
    'altgraph',
    'apyori',
    'astunparse',
    'AutoROM',
    'AutoROM.accept-rom-license',
    'av',
    'box2d-py',
    'certifi',
    'charset-normalizer',
    'click',
    'cloudpickle',
    'colorama',
    'contourpy',
    'Farama-Notifications',
    'filelock',
    'flatbuffers',
    'fonttools',
    'fsspec',
    'gast',
    'google-pasta',
    'grpcio',
    'gym',
    'gym-notices',
    'gymnasium',
    'h5py',
    'idna',
    'imageio',
    'imageio-ffmpeg',
    'importlib_resources',
    'Jinja2',
    'joblib',
    'keras',
    
    'libclang',
    'Markdown',
    'markdown-it-py',
    'MarkupSafe',
    
    'mdurl',
    'MiniSom',
    'ml-dtypes',
    
    'mpmath',
    'namex',
    'networkx',
    'nltk',
    
    'opt_einsum',
    'optree',
    
    'pandas',
    'pefile',
    'pillow',
    'pip',
    'protobuf',
    'psutil',
    'pygame',
    'Pygments',
    'pyinstaller',
    'pyinstaller-hooks-contrib',
    
    'python-dateutil',
    'pytz',
    'pywin32-ctypes',
    'qbstyles',
    'regex',
    'requests',
    'rich',
    'scikit-learn',
    
    'setuptools',
    
    'swig',
    'sympy',
    'tabulate',
    'tensorboard',
    'tensorboard-data-server',
    'tensorflow',
    'tensorflow_intel',
    'tensorflow-io-gcs-filesystem',
    
    'threadpoolctl',
    'torch',
    'torchvision',
    'tqdm',
    'typing_extensions',
    'tzdata',
    'urllib3',
    'Werkzeug',
    'wheel',
    'wrapt',
    'xgboost'
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas_list,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    includes=includes_list,
    excludes=excludes_list,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SpacecraftSimulator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['img\\icon.ico'],
)
